### ISSUE TITLE
Issue with the Netatmo API

### ISSUE THREAD

**Issue by fab-git-f** [tipok/netatmo_energy_exporter#5]
Hi there,

Since a few weeks my exporter doesn't work anymore with the following error :

Response: {"error":"unauthorized_client"}
could not get token for ...@....com oauth2 cannot fetch token : 400

Do any of you hear about somes changes at the netatmo level ? Are have any issue since a few weeks/months ?
I had to update the netatmo weather station exporter contaninerfor that reason and that did fix the issue.

Looks like netatmo did change the way API works.

Thanks for any help here!
F

**Comment by jnordberg** [comment]
Looks like the auth API this relies on was removed, it needs a refresh token now.

https://github.com/xperimental/netatmo-exporter/blob/master/doc/authentication.md#authentication

**Comment by tipok** [comment]
Unfortunately I'm not using this tool any more, therefore not updating it frequently.
I've updated it to use the refresh token flow, it should be working using this flow.

**Comment by fab-git-f** [comment]
Thank you Tipok, new container with refresh token works great !
Thanks for your time !

FYI. there's a typo in the README section :
--refre**hs**-token=${REFRESH_TOKEN} 

Cheers and thanks again!

**Comment by tipok** [comment]
Thanks for pointing out, should be fixed now
