### ISSUE TITLE
error in logs

### ISSUE THREAD

**Issue by DEEJCUK** [tipok/netatmo_energy_exporter#6]
thanks for the changes made to use the refresh token, i just found this recently and am looking at using it in prometheus, do you know what this means ?

`netatmo-energy-exporter  | 2023/12/20 09:02:22 Error during get home status: could not get data: could not find body: map[status:[34 111 107 34] time_server:[49 55 48 51 48 54 50 57 52 51]]
`
also, is there a grafana dashboard anywhere that utilises some of the metrics ?

**Comment by tipok** [comment]
As mentioned before, this isn't developed actively any more :( 
Anyway I'll try to check if I can find the root cause for this error.

Unfortunately there is no dashboard I'm aware of, but I would be happy if you could create a PR adding one.

**Comment by DEEJCUK** [comment]
That’s fair comment I just thought you might say “hey it’s this” and I can fix it but if it’s a pain don’t worry about it as it seems To work good enough to use
