### ISSUE TITLE
Authenticating error

### ISSUE THREAD

**Issue by daviddanko** [tipok/netatmo_energy_exporter#9]
Since 7th of June I am getting the following error.

2024/06/10 19:37:53 could not get homes data: could not get data: error during http request: Get "https://api.netatmo.com/api/homesdata": oauth2: "invalid_client"

I have tried to regenerate the refresh token but it didn't help. Did they change something again?

**Comment by giuliomagnifico** [comment]
Same error here, regenerating the token works but I have to do it once every 10-15 days. It's annoying, have you found a fix?

**Comment by daviddanko** [comment]
No. After each restart I have to regenerate the tokens.

**Comment by giuliomagnifico** [comment]
Hey @daviddanko, I created a fork that should work even if stopped and relaunched. It creates a new file (`netatmo_token.json`) to store the access token, refresh token, and expiration date, and reads it upon restart.

If you want to test/try:  
[https://github.com/giuliomagnifico/netatmo_energy_exporter/tree/master](https://github.com/giuliomagnifico/netatmo_energy_exporter/tree/master)

Hope this help.

PS: Sorry for the delay, but I only worked on this now that it's cold and I'm using again the thermostat, ahaha. I totally forgot about it during the summer! 🤣

**Comment by daviddanko** [comment]
Hi @giuliomagnifico, this is awesome! As I am not able to to open an issue/feature, I'm asking here. Are there any plans from your side to create a docker compose for it?

**Comment by giuliomagnifico** [comment]
@daviddanko I don't have Docker installed anywhere and I have no idea how to do it, but can't you just build the Docker image from my repo?

https://stackoverflow.com/questions/26753030/how-to-build-docker-image-from-github-repository

**Comment by daviddanko** [comment]
@giuliomagnifico, I certainly could, but incorporating this into a compose would make it significantly cleaner and more user-friendly. I'm confident it would attract more users that way.

**Comment by daviddanko** [comment]
> [@daviddanko](https://github.com/daviddanko) I don't have Docker installed anywhere and I have no idea how to do it, but can't you just build the Docker image from my repo?
> 
> https://stackoverflow.com/questions/26753030/how-to-build-docker-image-from-github-repository

hi @giuliomagnifico have you had the chance to create a docker compose? are you planning to do it?
